### ISSUE TITLE
Improve ComIntRep for high DPI

### ISSUE THREAD

**Issue by ItielMaN** [rizonesoft/ComIntRep#1]
![default](https://user-images.githubusercontent.com/18016656/33096708-a7feff9a-cf10-11e7-94fd-d5ffef95c467.png)
This is a screenshot taken from my Windows 10 x86, DPI set to 150%.

**Comment by ItielMaN** [comment]
![default](https://user-images.githubusercontent.com/18016656/33828141-934dac50-de73-11e7-990a-47dbc57e94b2.png)

See here- the icons in the dropdown menu are not aligned to each line:
![default](https://user-images.githubusercontent.com/18016656/33828166-b70392b8-de73-11e7-996a-70f3f3f50cd2.png)

**Comment by rizonesoft** [comment]
@ItielMaN I disable the DPI-aware feature in all upcoming releases. Should solve the issue.

**Comment by ItielMaN** [comment]
Thanks!
Any plans to re-implement it in the future?

**Comment by rizonesoft** [comment]
@ItielMaN The solution I came up with is not working as expected. If I find a proper solution, I will be making my software DPI aware again. But at the moment, I can't make any promises.
