### ISSUE TITLE
Translate to other language

### ISSUE THREAD

**Issue by ext5** [rizonesoft/ComIntRep#2]
I want to translate the program into Russian. The af.ini file is not suitable for this, I need the en.ini file

**Comment by rizonesoft** [comment]
I will prepare and send you the en.ini file wirhin 24 hours. Would I be
able to use your translation? Include it in the next release?

**Comment by rizonesoft** [comment]
I will prepare and send you the en.ini file within 24 hours.

**Comment by rizonesoft** [comment]
You can download the new version from https://www.rizonesoft.com/downloads/complete-internet-repair/ Please upload the translation here when you're done.

**Comment by ext5** [comment]
All done!
[ru.zip](https://github.com/rizonesoft/ComIntRep/files/1504073/ru.zip)

**Comment by rizonesoft** [comment]
@ext5 You are a star. Thank you for the translation.

**Comment by josebraund** [comment]
Please add SPanish or translate

**Comment by LaMoLa** [comment]
HI  Here is the Hungarian translation for Complete.Internet.Repair
Best regards from Budapest   LaMoLa
[hu.txt](https://github.com/rizonesoft/ComIntRep/files/1650116/hu.txt)

**Comment by hpwamr** [comment]
@rizonesoft 
Hello Derick,
I've corrected a few words in the french translation of "Complete Internet Repair".
Have a nice day :-)
hpwamr
[ComIntRep LangFile Fr.docx](https://github.com/rizonesoft/ComIntRep/files/1656898/ComIntRep.LangFile.Fr.docx)

**Comment by LaMoLa** [comment]
HI Derick. Something wrong. I sent You the Hungarian translation for Internet repair :-)

The hu.ini is for the Internet Repair


The  Hungarian translation for ThisIsMyFile 2.21 is not perfect. Here  is the correct for You. - Hungarian.ini


Best regards from Budapest   LaMoLa


________________________________
Feladó: hpwamr <notifications@github.com>
Elküldve: 2018. január 23. 18:06
Címzett: rizonesoft/ComIntRep
Másolatot kap: LaMoLa; Comment
Tárgy: Re: [rizonesoft/ComIntRep] Translate to other language (#2)


@rizonesoft<https://github.com/rizonesoft>
Hello Derick,
I've corrected a few words in the french translation of "Complete Internet Repair".
Have a nice day :-)
hpwamr
ComIntRep LangFile Fr.docx<https://github.com/rizonesoft/ComIntRep/files/1656898/ComIntRep.LangFile.Fr.docx>

**Comment by ext5** [comment]
I updated ru.lng

[ru.zip](https://github.com/rizonesoft/ComIntRep/files/2456426/ru.zip)

**Comment by LaMoLa** [comment]
HI Derick
Here is the renewed Hungarian translation + for Firemin
https://mega.nz/fm/RoQjAQiB

[Hungarian-New.lang.zip](https://github.com/rizonesoft/ComIntRep/files/2499489/Hungarian-New.lang.zip)
