### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Losses** [rizonesoft/ComIntRep#8]
Which license does the source code use? I've a opensource tool under MIT license, could it integrate this tool?

**Comment by Losses** [comment]
Ohhhhhh... I found the license under document dir, but why not putting it into root dir so GitHub will detect it automatically😂

**Comment by rizonesoft** [comment]
It uses the GNU General Public License. It can integrate the tool.

**Comment by Losses** [comment]
Okay, Thanks for your kindly help!
